use super::{
    account,
    money::{Currency, Fiat},
};

#[derive(Clone, Debug)]
pub enum Message {
    AddCrypto,
    AddFiat,
    AddGroup,
    AddMetal,
    AddStockPlus,
    Account(account::Message),
    Back,
    ChartWeek,
    ChartMonth,
    ChartYear,
    ChartAll,
    ChangeAccountName(String),
    ChangeProjectMonths(String),
    Checkbox((usize, bool)),
    Configuration,
    Delete(usize),
    DeleteGroup(usize),
    FileLoad,
    FileSaveAs,
    GetPrice(usize),
    GetPriceAll,
    ImportBoa(usize),
    ImportInvestor360,
    OpenBoaUrl,
    OpenInvestor360Url,
    UpdateAccountName(usize),
    UpdateCurrency(Currency),
    UpdateCryptoCurrency(Fiat),
    UpdateCryptoDescription(String),
    UpdateCryptoSymbol(String),
    UpdateFiat(Fiat),
    UpdateMetalCurrency(Fiat),
    UpdateMetalDescription(String),
    UpdateMetalSymbol(String),
    UpdateStockPlusDescription(String),
    UpdateStockPlusSymbol(String),
    SelectAccount(usize),
    SelectAccountSecondary(usize),
    SubmitAccount,
    Exit,
}
